FROM ubuntu:14.04
MAINTAINER Xiaodong "xiaodong.liu@intel.com"
ENV REFRESHED_AT 2017-03-24
ENV http_proxy http://proxy-prc.intel.com:911/
ADD sources.list.trusty /etc/apt/sources.list
RUN apt-get -yqq update
EXPOSE 80

